### ISSUE TITLE
Allow exporting to json / ron / yaml?

### ISSUE THREAD

**Issue by lucasmerlin** [grantshandy/egui-themer#1]
Hi! First of all, awesome project! 
I actually had the same idea a couple of days ago, and when I started working on it today I found your repo. 
I think egui could really benefit from having a good theme editor and a easy way to share themes created by different users.

My idea was to export the themes as a json / ron / yaml file, so you could easily share themes and even make egui apps themable by users without having to recompile the app.
I planned to have a library part that can parse / import the json theme files and the editor that would be provided as a web app to quickly create themes, but could also be included in other apps if the users should be able to create themes themselves. 
Since egui already has serde on the style structs the import / export should be pretty trivial.

We could eventually even have online gallery where different themes could be shared and previewed in the browser.

But generating rust code of course is more flexible if the user wants to make changes that aren't available in the editor.

I'm happy to contribute to this project if this aligns with your ideas!

**Comment by grantshandy** [comment]
I agree that json/toml/yaml export should be added. This was my original plan for this project. However, I was unable to parse/deserialize those formats at compile time or in a macro, so I decided against it at the time. My goal for this project was to enable themeing without any additional libraries or runtime costs.

You're right, serde serialization of the Style struct is extremely simple. Once I complete the editor's new menu I'll add a combo box for JSON/YAML/TOML export and let the consumer parse it using their own DeSer library, I'm hesitant to add to the already existing set of egui theme file format libraries 👍.

**Comment by grantshandy** [comment]
A little late but you can now export to JSON via the export menu 👍🏽.
